### ISSUE TITLE
Crash on navigation for compound buttons

### ISSUE THREAD

**Issue by vincent-karuri** [OpenSRP/opensrp-client-native-form#540]
```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONArray org.json.JSONObject.getJSONArray(java.lang.String)' on a null object reference
        at com.vijay.jsonwizard.activities.JsonFormActivity.checkBoxWriteValue(JsonFormActivity.java:1000)
        at com.vijay.jsonwizard.activities.JsonFormActivity.writeValue(JsonFormActivity.java:189)
        at com.vijay.jsonwizard.fragments.JsonFormFragment.writeValue(JsonFormFragment.java:549)
        at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.onCheckedChanged(JsonFormFragmentPresenter.java:968)
        at com.vijay.jsonwizard.fragments.JsonFormFragment.onCheckedChanged(JsonFormFragment.java:741)
        at android.widget.CompoundButton.setChecked(CompoundButton.java:182)
        at com.vijay.jsonwizard.widgets.CheckBoxFactory.addCheckBoxOptionsElements(CheckBoxFactory.java:209)
        at com.vijay.jsonwizard.widgets.CheckBoxFactory.attachJson(CheckBoxFactory.java:123)
        at com.vijay.jsonwizard.widgets.CheckBoxFactory.getViewsFromJson(CheckBoxFactory.java:78)
        at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchViews(JsonFormInteractor.java:223)
        at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchFields(JsonFormInteractor.java:209)
        at com.vijay.jsonwizard.interactors.JsonFormInteractor.fetchFormElements(JsonFormInteractor.java:163)
        at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.executeRefreshLogicForNextStep(JsonFormFragmentPresenter.java:492)
        at com.vijay.jsonwizard.presenters.JsonFormFragmentPresenter.onNextClick(JsonFormFragmentPresenter.java:361)
        at com.vijay.jsonwizard.fragments.JsonFormFragment.next(JsonFormFragment.java:422)
```

This exception occurs when one selects a checkbox or radio button on a page and navigates a step back then one step forward to the initial page i.e. select a checkbox or radio button on page 2, navigate back to page 1 then navigate forward to page 2, crash occurs.

**Comment by vincent-karuri** [comment]
@bennsimon  do you have an idea what's happening here?
