### ISSUE TITLE
Next button not working on new version 2.1.13

### ISSUE THREAD

**Issue by SebaMutuku** [opensrp/opensrp-client-native-form#612]
Expected. On click next button a next fragment should be launched and render with a JSON  Form,
however with version 2.1.13 of native form, I am getting below exception.
"**2022-01-03 15:06:50.159 5022-5192/org.smartregister.anc E/JsonFormFragment:  --> next
    java.lang.RuntimeException: Can't create handler inside thread Thread[pool-42-thread-1,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:227)
        at android.os.Handler.<init>(Handler.java:153)
        at com.vijay.jsonwizard.fragments.JsonFormFragment.<init>(JsonFormFragment.java:89)
        at com.vijay.jsonwizard.fragments.JsonWizardFormFragment.<init>(JsonWizardFormFragment.java:35)
        at org.smartregister.anc.library.fragment.ContactWizardJsonFormFragment.<init>(ContactWizardJsonFormFragment.java:46)
        at org.smartregister.anc.library.fragment.ContactWizardJsonFormFragment.getFormFragment(ContactWizardJsonFormFragment.java:55)
        at org.smartregister.anc.library.presenter.ContactWizardJsonFormFragmentPresenter.moveToNextWizardStep(ContactWizardJsonFormFragmentPresenter.java:40)
        at com.vijay.jsonwizard.presenters.JsonWizardFormFragmentPresenter.onNextClick(JsonWizardFormFragmentPresenter.java:27)
        at com.vijay.jsonwizard.fragments.JsonFormFragment.next(JsonFormFragment.java:476)
        at org.smartregister.anc.library.fragment.ContactWizardJsonFormFragment$BottomNavigationListener$2.run(ContactWizardJsonFormFragment.java:359)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)**"

client-app :WHO-ANC-CLIENT
test form ;anc_test.json
Tab : Tests tab under start contact.

**Comment by dubdabasoduba** [comment]
The form wizard pieces of Native Forms seems broken.  

**How to test**
- Run the Native forms sample app. 
- Load any form with a wizard,  fill in the required fields then click on next. 
- The loading popup will show up but nothing else happens after that.  

**Acceptance criteria** 
- Run the Native forms sample app. 
- Load any form with a wizard,  fill in the required fields then click on next. 
- The loading popup should show up then move to the next form step.
